"""Product-B biological-constraint and paired answer-check prototype."""

from .calibration import (
    CalibrationDecision,
    CalibrationState,
    CalibrationTaxonResult,
    calibrate_reference_ceiling,
)
from .crosscheck import (
    PairedAnswerCheckDecision,
    PairedCheckState,
    classify_paired_answer_check,
    reciprocal_containment_discordance,
)
from .invariants import (
    InvariantState,
    PreflightResult,
    ProcedureDescriptor,
    breadth_ratio_pair,
    centroid_separation_pair,
    classify_directed_invariant,
    directed_containment,
    response_blind_differentiability_precheck,
    schoener_d_pair,
    support_breadth,
)
from .mutual import (
    ConstraintClass,
    MutualContainmentResult,
    MutualInvariantDecision,
    classify_mutual_obligacy,
    mutual_obligacy_containment,
    rank_profile_discordance_pair,
)
from .observation_modes import (
    ALLOWED_GBIF_OBSERVATION_MODES,
    EXPECTED_PARTITION_FIELD,
    SameTargetObservationSplit,
    validate_same_target_observation_split,
)
from .paired_relations import (
    PairedRelationContract,
    PairedRelationKind,
    RelationStrength,
    bidirectional_containment_discordance,
    containment_discordance,
    overlap_discordance,
    validate_paired_relation_contract,
)
from .relation_space import (
    AdaptedAnswer,
    AnswerEstimand,
    EcologicalAnswerContract,
    EstimatorPolicy,
    RelationSpaceContract,
    RelationSpaceKind,
    RelationSpacePair,
    align_adapted_answers,
    directional_containment_on_relation_space,
    validate_adapted_answer,
    validate_paired_relation_with_space,
    validate_relation_space_contract,
)

__all__ = [
    "CalibrationDecision",
    "CalibrationState",
    "CalibrationTaxonResult",
    "calibrate_reference_ceiling",
    "PairedAnswerCheckDecision",
    "PairedCheckState",
    "classify_paired_answer_check",
    "reciprocal_containment_discordance",
    "InvariantState",
    "PreflightResult",
    "ProcedureDescriptor",
    "breadth_ratio_pair",
    "centroid_separation_pair",
    "classify_directed_invariant",
    "directed_containment",
    "response_blind_differentiability_precheck",
    "schoener_d_pair",
    "support_breadth",
    "ConstraintClass",
    "MutualContainmentResult",
    "MutualInvariantDecision",
    "classify_mutual_obligacy",
    "mutual_obligacy_containment",
    "rank_profile_discordance_pair",
    "ALLOWED_GBIF_OBSERVATION_MODES",
    "EXPECTED_PARTITION_FIELD",
    "SameTargetObservationSplit",
    "validate_same_target_observation_split",
    "PairedRelationContract",
    "PairedRelationKind",
    "RelationStrength",
    "validate_paired_relation_contract",
    "containment_discordance",
    "bidirectional_containment_discordance",
    "overlap_discordance",
    "AdaptedAnswer",
    "AnswerEstimand",
    "EcologicalAnswerContract",
    "EstimatorPolicy",
    "RelationSpaceContract",
    "RelationSpaceKind",
    "RelationSpacePair",
    "align_adapted_answers",
    "directional_containment_on_relation_space",
    "validate_adapted_answer",
    "validate_paired_relation_with_space",
    "validate_relation_space_contract",
]
